project:
  type: website
  output-dir: docs

# Meta
description-meta: "Dr. Lynée Turek-Hankins is..."
author-meta: "Lynée Turek-Hankins"

website:
  title: "Dr. Lynée Turek-Hankins"
  image: "files/images/headshot-1.jpg"
  description: "Dr. Lynée Turek-Hankins is..."
 
  navbar:
    background: "#3E715F"

    left:
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: About me
            href: about_me.qmd
          - text: Contact
            href: contact.qmd   
          - text: CV
            href: files/lynee_turek_hankins_CV.pdf 
            target: _blank 
      - text: Research
        menu:
          - text: Publications
            href: publications.qmd
          - text: Presentations
            href: presentations.qmd
      - text: Engagement
        menu:
        - text: Events and service
          href: events.qmd 
        - text: In the news
          href: media.qmd      


  page-navigation: true
  
  page-footer: 
    left: "[Lynée Turek-Hankins](http://lyneeturekhankins.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/llturekhankins/lyneeturekhankins.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://lyneeturekhankins.com"
  
  google-analytics:
    tracking-id: "Sd3LQW0AAAAJ"  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/lyneeturekhankins\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

